import pyautogui
print(pyautogui.size())
print(pyautogui.position())
org_position = pyautogui.position()
print(org_position)
pyautogui.moveTo(100, 1040, duration = 1)
pyautogui.click()
pyautogui.typewrite("cmd")
pyautogui.hotkey("enter")
pyautogui.moveTo(500, 400, duration = 1)
pyautogui.click()
print(pyautogui.position())
pyautogui.typewrite("python C:\\Users\\ZMO-WIN-PriteshG-01\\Documents\\training\\eee.py")
pyautogui.hotkey("enter")